### ISSUE TITLE
In RTL languages checked checklist items move to the right

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1572]
When checking a checklist item in rtl languages the item moves to the left:
https://imgur.com/a/WNO1yAi

### Expected
Should be right-aligned

### Observed
It is right-aligned

**Comment by belcherj** [comment]
`- [x] RTL Language` is determined to be LTR.  This function only looks at the first letter character which in this case is an `x` and determines it to be LTR. https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/unicode/UnicodeBidi.js#L198

**Comment by hadisfr** [comment]
Any progress here?

In recent versions problem appears in more general use cases:

Here is a more detailed example:

```md
تست می‌کنیم

- یک مثال دیگر
* یک مثال

* [x] یک مثال جدید
* [ ] یک مثال جدید دیگر


* [ ] test
*  [X] another test

```

GitHub MarkDown rendering:
<hr>
تست می‌کنیم

- یک مثال دیگر
* یک مثال

* [x] یک مثال جدید
* [ ] یک مثال جدید دیگر

* [ ] test
*  [X] another test

<hr>

![image](https://user-images.githubusercontent.com/24562441/103808310-06c28200-506d-11eb-8a36-8fed7bf0f97b.png)

SmpleNote Electron Edit:
![image](https://user-images.githubusercontent.com/24562441/103808478-49845a00-506d-11eb-9c27-28f3d4e06060.png)

SimpleNote Electron Preview:
![image](https://user-images.githubusercontent.com/24562441/103808404-2b1e5e80-506d-11eb-8437-6088ad506d73.png)

SimpleNote Android Edit:
![image](https://user-images.githubusercontent.com/24562441/103808549-61f47480-506d-11eb-891b-4a73c5dbda05.png)

SimpleNote Android Preview:
![image](https://user-images.githubusercontent.com/24562441/103808593-733d8100-506d-11eb-9ad4-258b058cb62b.png)

Expectation:
![image](https://user-images.githubusercontent.com/24562441/103809163-5c4b5e80-506e-11eb-9923-27905b86d360.png)
