### ISSUE TITLE
Tracking Issue: Stop directly mutating app state

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#1614]
The app is ostensibly based on the Redux UI model which assumes atomic state transitions supplying immutable app states. Unfortunately it's the case that in several places throughout the app we are directly mutating that app state. This creates concurrency errors by allowing the app to exist where _partial_ state updates have been applied.

While it's not entirely clear how many, if any, bugs are due to this unidiomatic mutation, it's clear that the mutation further complicates the data flow through the app and makes it hard to determine _if_ these defects are the cause for inconsistencies we observe.

As part of untangling our data flows I'd like to remove all of these places of direct mutation and replace them with idiomatic _immutable swaps_. When this work is finished it should be easier to trace updates throughout the app and we will know that concurrency errors are not due to this concern.

 - [x] `app-state::pinNote` - `note.data.systemTags` ~#1611~ #1615 
 - [x] `app-state::markdownNote` - `note.data.systemTags` #1615
 - [x] `app-state::publishNote` - `note.data.systemTags` #1615
 - [x] `app-state::noteUpdatedRemotely` - `note.data` #1634 
 - [x] `app-state::updateNoteContent` - `note.data.content`, `note.data.modificationDate` #1634 
 - [x] `app-state::trashNote` - `note.data.systemTags` ~#1613~ #1615
 - [x] `domain/notes::updateNoteTags` - `note.data.tags`, `note.data.modificationDate` #1639
 - [x] `domain/tags::renameTag` - `note.data.tags` #1638
 - [x] `domain/tags::trashTag` - `note.data.tags` #1638

**Comment by belcherj** [comment]
Closing as @dmsnell fixed what he found!
