### ISSUE TITLE
Mac app feature parity

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#445]
To keep track of everything we need to do for Mac app feature parity. Feel free to add to this list.

- [ ]  #267 - Resize divider between list and notes
- [ ]  #224 - Use shift key to select more than one note
- [ ]  #44 - Drag to select multiple notes
- [ ]  #37 - Keyboard bindings/shortcuts
- [ ] #433 - Toggle tags list sidebar
- [x] #411 - X icon to clear search 
- [ ] #13 - Share content to/from app natively
- [ ] #368 - Link detection
- [x] #398 autocomplete lists
- [ ] #412 - Figure out which keyboard shortcut to focus search
- [ ] Send notes via email (can select multiple notes via #224 and #44)
- [ ] Right click note in note list to delete note

This is now a Project

https://github.com/Automattic/simplenote-electron/projects/2

**Comment by roundhill** [comment]
#1337 - Sync like a boss

**Comment by owcz** [comment]
For parity,
- [ ] #412 - Ctrl+L to toggle search field focus
though someone has argued that the Mac default should change too

**Comment by drw158** [comment]
Thanks, @owcz, added to the original post.

**Comment by nfcampos** [comment]
I guess list autocompletion is needed as well for parity https://github.com/Automattic/simplenote-electron/pull/398

**Comment by TwisterMc** [comment]
Markdown would be nice in the Mac app too.
https://github.com/Automattic/simplenote-electron/issues/329

**Comment by crankygeologist** [comment]
Spelling and grammar functionality, please.

**Comment by owcz** [comment]
Also #301: search within note (the macOS native client has both Cmd+F to search within a single note and Cmd+L for the app's main search bar, to search between notes)

**Comment by jamiepalatnik** [comment]
Report from 835615-zen:  

Beta version 1.0.8 released 31 January 2017. May also be known as the ‘Electron’ release.
In the official release:
CMD+F: sub window dialog opens, Finds text in the single note.
CMD+OPT+F: moves the cursor to the ‘all notes’ search box.
Neither of these shortcuts works in the ‘Electron’ beta.

**Comment by crankygeologist** [comment]
Notes saved to PDF are just a bitmap of the text. Please see:

https://github.com/Automattic/simplenote-electron/issues/1232#issue-421147472

**Comment by bummytime** [comment]
Closing this issue since the[ project noted above](https://github.com/Automattic/simplenote-electron/projects/2) exists.
