### ISSUE TITLE
Shortcut Documentation

### ISSUE THREAD

**Issue by AntonioFasano** [Automattic/simplenote-electron#700]
Shortcut documentation is outdated (especially for Linux/Windows).
See [simplenote.com/help/#shortcuts](https://simplenote.com/help/#shortcuts). There is also a mismatch in FAQ headers. 

IMHO shortcuts are absolutely necessary for productivity apps and documenting them is a necessary step to _make them consistent_.

**Comment by mirka** [comment]
### TODO
- [ ] comb through the code and figure out what all the shortcuts are
- [ ] sort them into groups (Navigation, Views, Note, etc.)
- [ ] design a keyboard shortcut cheatsheet (modal dialog) to add in the app
- [ ] cheatsheet should be smart about platform-specific shortcuts
- [ ] add it under the Help menu (we’ll only need it in Electron for now)
- [ ] remove the shortcut documentation at [simplenote.com/help/#shortcuts](https://simplenote.com/help/#shortcuts)

**Comment by rakhi2104** [comment]
I'm taking this up :1st_place_medal:

**Comment by mirka** [comment]
@rakhi2104 Awesome! Even partial help with the first one or two tasks would be appreciated. You can post the results in this thread 🙂

**Comment by rakhi2104** [comment]
Definitely :sunglasses: 
Don't know why the third one is also so attractive :drooling_face:

**Comment by rakhi2104** [comment]
Hey @mirka, I made a board of shortcuts to classify between different categories.
Any changes to be made ?
![simplenote-shortcuts](https://user-images.githubusercontent.com/17671710/47256082-81585480-d497-11e8-8352-b5f1697e2bcd.png)

**Comment by mirka** [comment]
Yay, thank you @rakhi2104 ! 😂 

For the documentation, let's remove some of the ones that are not really specific to our app. So remove Minimize, Close, Exit, and Undo, Redo, Cut, Copy, Paste, Select All, Print.

> Previous note, Next note

I'm planning on removing the Ctrl+Shift+Up/Down shortcuts for this, as per #798. So let's keep just the J/K ones.

We also seem to have

Navigation:
- Ctrl+T - Tag field

Note:
- Ctrl+Shift+P - Toggle Markdown preview

**Comment by rakhi2104** [comment]
Oh, thanks ! Will make those changes.

**Comment by mirka** [comment]
Adding `Alt + Ctrl + C` for Insert Checklist

**Comment by AntonioFasano** [comment]
Thanks for the good work!

A couple of suggestions:

1) The [FAQ](https://simplenote.com/help/) entry still says only:
    What are the keyboard shortcuts for the Mac app?

2) As I understand, Open Tag List: Ctrl+Shisft+T, should probably  be Toggle Tag List. 

3) I note that when I toggle the Tag List view, the note panel dims, suggesting I can't type there, while  I can.  Instead, I can do nothing on tags  with the keyboard, apart toggling them out. It would be nice to be able to select them.

**Comment by b3u** [comment]
@rakhi2104 Do you need any help with this?

**Comment by b3u** [comment]
See http://simp.ly/p/rsnDV7 for a list (I don't know the architecture of the code well, so it may be incomplete)

**Comment by AntonioFasano** [comment]
> See http://simp.ly/p/rsnDV7 for a list (I don't know the architecture of the code well, so it may be incomplete)

How to move to the next/previous note?

**Comment by b3u** [comment]
I don't think you can right now. Good suggestion, though. Open an issue for that, I guess.

**Comment by b3u** [comment]
@mirka what's the status on this? I think that adding a shortcut page on the website with an updated list of would be easy and quick.

**Comment by dmsnell** [comment]
Thanks so much @rakhi2104 for the chart - I adopted its layout in #1983
