### ISSUE TITLE
Improve codebase for maintainability

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#822]
## General

- [x] Remove unused dependencies #829 
- [x] Add all vendor packages to the DLL (or find other ways to cut down the build time) #830 #831 #834  
- [x] Simplify Babel config #828 
- [x] Tie scss files to components #832 
- [x] Set webpack mode to development when in dev #870 

### Can wait
- [ ] Restructure light/dark theme styles so `theme-` classNames don’t have to be passed in to components
- [ ] Clarify scoping of CSS classes to components (Make sure CSS classes are named according to their components, à la [wp-calypso](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md), and that state-dependent rules are clearly scoped) #958
- [ ] Move all React components into `lib/components/`

### Priority high (for Focus Mode)
- app.jsx
  - [x] Factor out dialog rendering #843 
  - [x] Factor out undo/redo context menu #821 
  - [x] Move `!hasNotes` render content to respective components (note-list, note-detail, note-toolbar, note-editor) #846 
- note-editor.jsx
  - [x] Make connected container for NoteToolbar #853 
  - [x] Connect RevisionSelector to redux #852 

### Can wait
- [ ] auth.jsx
- [ ] flux/app-state.js
- [ ] dialogs/share.jsx
- [ ] note-info.jsx (easy)
- [ ] note-list.jsx
- [x] note-toolbar.jsx (Refactor toolbar buttons, and see if props can be reduced or reorganized)

**Comment by belcherj** [comment]
Closing for now. Some of this still makes sense, but I think we should open individual issues for each task.
