### ISSUE TITLE
Fixes for Web Version

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#855]
I've evaluated the app for things that we'd need to do in order for it to work well on the web:

- [x] Add an easy way to get to Settings (maybe in a permanent footer like the current web app?) #1106  
- [x] Add export notes button/link somewhere #1111 
- [x] Sign out should take you to the app engine sign-in page. #1091
- [x] Add cross-browser support (Babel, Autoprefixer, etc.) #1055 #1064 #1081 #1082 
- [x] Code splitting #902 #1014 
- [x] e-mail address doesn't display in settings #1091 
- [x] simplify print styles #1013 
- [x] make the export file download instead of fs.writeFile #1083

**Comment by rakhi2104** [comment]
Is it necessary that 'Sign In' link is present again on the signin page ?
:repeat:

**Comment by rakhi2104** [comment]
> Add an easy way to get to Settings (maybe in a permanent footer like the current web app?)

the `is-electron` css class hides it in the electron App.
So, removing this will finish the work I believe.

**Comment by rakhi2104** [comment]
Should the Settings option hide inside the navigation panel ? (this can be accessed only by selecting the tags icon, which is disturbing)
Why not make it available in the notes and search panel itself ? 
@mirka @roundhill

**Comment by mirka** [comment]
> Why not make it available in the notes and search panel itself ?

Yeah, I think that's better than in the navigation panel too. I haven't decided exactly what's best though. There are other places where it could be 🤔
