### ISSUE TITLE
Task list checkboxes not rendering in preview

### ISSUE THREAD

**Issue by forstmeier** [Automattic/simplenote-electron#914]
#### Steps to reproduce
1. Create a task list using GFM

```
- [ ] this is a task
- [ ] here is another one
- [ ] the last task
```

2. Click "Preview" on macOS, web app, Android device
3. Renders as "- [ ]" instead of the checkbox

#### What I expected

Something like this:

![image](https://user-images.githubusercontent.com/13358530/46906791-33f84800-ced7-11e8-8e3a-13cd4e408cc9.png)

#### What happened instead

Simplenote web app:
![image](https://user-images.githubusercontent.com/13358530/46906802-54c09d80-ced7-11e8-95c7-7f5bcd1dc43e.png)

MacOS client:

![image](https://user-images.githubusercontent.com/13358530/46906824-77eb4d00-ced7-11e8-89b8-c0e32f06c7b1.png)

Android:

![image](https://user-images.githubusercontent.com/13358530/46906847-d57f9980-ced7-11e8-8d19-a86b3a49d474.png)

#### OS version

- Simplenote web app
- macOS High Sierra version 10.13.6
- Android version 9 on Google Pixel 2
