### ISSUE TITLE
Evernote importer

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#916]
Carrying on from #365 

## TODO
- [x] design importer dialog ([Sketch prototype](https://sketch.cloud/s/aGbWP/n7DZdz/play)) @mirka 
- [x] implement importer dialog #957 @mirka 
- [x] add `Import From ▶` `Evernote...` item in the File menu to trigger the dialog @mirka 
- [x] write the parser #940 @roundhill 
- [x] write the importer #922 @roundhill 

I think we should keep it as simple as possible for the first iteration, and we can add enhancements later.

**Comment by SeanKilleen** [comment]
In terms of the parsing, this project may help: https://github.com/claytron/ever2simple
